# Generated by Django 3.1.3 on 2021-03-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210324_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.recipe'),
        ),
    ]
