# Generated by Django 3.1.3 on 2021-03-24 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210324_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='core.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='core.units'),
        ),
    ]
